### ISSUE TITLE
Rename plugin to mathjax?

### ISSUE THREAD

**Issue by karger** [DmitrySharabin/mavo-math#1]
This plugin is very mathjax specific.  Any reason not to call it mathjax instead of the more ambiguous math?

**Comment by DmitrySharabin** [comment]
That was the first name I gave the plugin. Later, I decided to use more short one and renamed it. I absolutely don't mind to rename it. Moreover, I believe it will harmonize the plugin name with the names of other plugins we already have.

Thanks!

**Comment by DmitrySharabin** [comment]
Done!
